import type { CaseItem } from '@/types'

export const useRouletteSore = defineStore('roulette', () => {
  const caseItems = ref<CaseItem[]>([
    {
      id: '1',
      name: 'Golden Dragon',
      image: '/images/template/case-item.png',
      probability: 0.5,
      tag: { text: 'Legendary', view: 'pink' },
      abilities: ['mega-neon', 'fly', 'ride'],
    },
    {
      id: '2',
      name: 'Shadow Wolf',
      image: '/images/template/case-item.png',
      probability: 1.2,
      tag: { text: 'Ultra Rare', view: 'red' },
      abilities: ['neon', 'fly'],
    },
    {
      id: '3',
      name: 'Frost Unicorn',
      image: '/images/template/case-item.png',
      probability: 0.9,
      tag: { text: 'Legendary', view: 'primary' },
      abilities: ['mega-neon', 'fly', 'neon'],
    },
    {
      id: '4',
      name: 'Flame Tiger',
      image: '/images/template/case-item.png',
      probability: 2.5,
      tag: { text: 'Rare', view: 'yellow' },
      abilities: ['ride'],
    },
    {
      id: '5',
      name: 'Crystal Penguin',
      image: '/images/template/case-item.png',
      probability: 3.8,
      tag: { text: 'Uncommon', view: 'pink' },
      abilities: ['neon'],
    },
    {
      id: '6',
      name: 'Midnight Bat',
      image: '/images/template/case-item.png',
      probability: 4.2,
      tag: { text: 'Rare', view: 'pink' },
      abilities: ['fly', 'ride'],
    },
    {
      id: '7',
      name: 'Sky Serpent',
      image: '/images/template/case-item.png',
      probability: 0.7,
      tag: { text: 'Legendary', view: 'pink' },
      abilities: ['mega-neon', 'fly'],
    },
    {
      id: '8',
      name: 'Candy Cat',
      image: '/images/template/case-item.png',
      probability: 5.5,
      tag: { text: 'Common', view: 'pink' },
      abilities: [],
    },
    {
      id: '9',
      name: 'Robo Dog',
      image: '/images/template/case-item.png',
      probability: 1.8,
      tag: { text: 'Ultra Rare', view: 'pink' },
      abilities: ['ride', 'neon'],
    },
    {
      id: '10',
      name: 'Emerald Tortoise',
      image: '/images/template/case-item.png',
      probability: 3.1,
      tag: { text: 'Uncommon', view: 'pink' },
      abilities: ['neon'],
    },
    {
      id: '11',
      name: 'Blizzard Owl',
      image: '/images/template/case-item.png',
      probability: 0.6,
      tag: { text: 'Legendary', view: 'pink' },
      abilities: ['mega-neon', 'fly', 'ride'],
    },
    {
      id: '12',
      name: 'Lava Golem',
      image: '/images/template/case-item.png',
      probability: 2.3,
      tag: { text: 'Rare', view: 'pink' },
      abilities: ['ride'],
    },
    {
      id: '13',
      name: 'Rainbow Fox',
      image: '/images/template/case-item.png',
      probability: 1.0,
      tag: { text: 'Ultra Rare', view: 'pink' },
      abilities: ['neon', 'ride'],
    },
    {
      id: '14',
      name: 'Snow Leopard',
      image: '/images/template/case-item.png',
      probability: 4.0,
      tag: { text: 'Uncommon', view: 'pink' },
      abilities: ['neon'],
    },
    {
      id: '15',
      name: 'Galaxy Phoenix',
      image: '/images/template/case-item.png',
      probability: 0.3,
      tag: { text: 'Mythic', view: 'pink' },
      abilities: ['mega-neon', 'fly', 'ride', 'neon'],
    },
  ])

  return {
    caseItems,
  }
})
